# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikes',
            fields=[
                ('SKU', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='No description available.', max_length=180)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('0', 'Road Bike'), ('1', 'Mountain Bike'), ('2', 'Hybrid Bike'), ('3', 'City Bike'), ('4', 'Others')], max_length=1)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
