# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171029_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='type',
            field=models.CharField(default='others', max_length=25),
        ),
    ]
