# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171030_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
