# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20171030_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(max_length=250, upload_to=''),
        ),
    ]
