# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20171030_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
