# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20171030_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
